name: Auto Commit Bot

on:
  schedule:
    - cron: "0 17 * * *"   # 1:00 AM Philippine time
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          echo "- $(date): worked on personal projects" >> journal.md

      - name: Commit changes
        run: |
          git config user.name "gb8462"
          git config user.email "gb8462@users.noreply.github.com"
          git add .
          git commit -m "daily notes" || echo "No changes"
          git push
